#pragma once

// Icon IDs must not contain any gaps!
#define IDI_SH_DEFAULT                 1
#define IDI_SH_AAC                     2
#define IDI_SH_AC3                     3
#define IDI_SH_AIFF                    4
#define IDI_SH_ALAC                    5
#define IDI_SH_AMR                     6
#define IDI_SH_APE                     7
#define IDI_SH_AU                      8
#define IDI_SH_AVI                     9
#define IDI_SH_BINK                   10
#define IDI_SH_CDA                    11
#define IDI_SH_DSM                    12
#define IDI_SH_DTS                    13
#define IDI_SH_FLAC                   14
#define IDI_SH_FLIC                   15
#define IDI_SH_FLV                    16
#define IDI_SH_IFO                    17
#define IDI_SH_IVF                    18
#define IDI_SH_MIDI                   19
#define IDI_SH_MKA                    20
#define IDI_SH_MKV                    21
#define IDI_SH_MOV                    22
#define IDI_SH_MP3                    23
#define IDI_SH_MP4                    24
#define IDI_SH_MPA                    25
#define IDI_SH_MPC                    26
#define IDI_SH_MPEG                   27
#define IDI_SH_OFR                    28
#define IDI_SH_OGG                    29
#define IDI_SH_OGM                    30
#define IDI_SH_PLAYLIST               31
#define IDI_SH_RA                     32
#define IDI_SH_RM                     33
#define IDI_SH_RT                     34
#define IDI_SH_SMK                    35
#define IDI_SH_SWF                    36
#define IDI_SH_TS                     37
#define IDI_SH_TTA                    38
#define IDI_SH_VOB                    39
#define IDI_SH_WAV                    40
#define IDI_SH_WEBM                   41
#define IDI_SH_WMA                    42
#define IDI_SH_WMV                    43
#define IDI_SH_WV                     44

#define IDS_SH_AC3                   502
#define IDS_SH_AIFF                  503
#define IDS_SH_ALAC                  504
#define IDS_SH_AMR                   505
#define IDS_SH_APE                   506
#define IDS_SH_AU                    507
#define IDS_SH_AVI                   508
#define IDS_SH_BINK                  509
#define IDS_SH_CDA                   510
#define IDS_SH_DSM                   511
#define IDS_SH_DTS                   512
#define IDS_SH_FLAC                  513
#define IDS_SH_FLIC                  514
#define IDS_SH_FLV                   515
#define IDS_SH_IFO                   516
#define IDS_SH_IVF                   517
#define IDS_SH_MIDI                  518
#define IDS_SH_MKA                   519
#define IDS_SH_MKV                   520
#define IDS_SH_MOV                   521
#define IDS_SH_MP3                   522
#define IDS_SH_MP4                   523
#define IDS_SH_MPA                   524
#define IDS_SH_MPC                   525
#define IDS_SH_MPG                   526
#define IDS_SH_OFR                   527
#define IDS_SH_OGG                   528
#define IDS_SH_OGM                   529
#define IDS_SH_PLAYLIST              530
#define IDS_SH_RA                    531
#define IDS_SH_RM                    532
#define IDS_SH_RT                    533
#define IDS_SH_SMK                   534
#define IDS_SH_SWF                   535
#define IDS_SH_TS                    536
#define IDS_SH_TTA                   537
#define IDS_SH_VOB                   538
#define IDS_SH_WAV                   539
#define IDS_SH_WEBM                  540
#define IDS_SH_WMA                   541
#define IDS_SH_WMV                   542
#define IDS_SH_WV                    543
#define IDS_SH_3GP                   544
#define IDS_SH_3G2                   545
#define IDS_SH_VIDEOF                546
#define IDS_SH_M4A                   547
#define IDS_SH_OPUS                  548
#define IDS_SH_TAK                   549
#define IDS_SH_AUDIOF                550
#define IDS_SH_PLS                   551
#define IDS_SH_BDMV                  552
//#define IDS_SH_RAR                 553
#define IDS_SH_MXF                   554

#define IDS_SH_RTP                  1001
#define IDS_SH_MMS                  1002
#define IDS_SH_RTMP                 1003
#define IDS_SH_RTSP                 1004

#define IDS_SH_AUTOPLAY_VIDEOFILES  1501
#define IDS_SH_AUTOPLAY_MUSICFILES  1502
#define IDS_SH_AUTOPLAY_AUDIOCD     1503
#define IDS_SH_AUTOPLAY_DVDMOVIE    1504

#define IDS_SH_PLAY                 2001
#define IDS_SH_ENQUEUE              2002

#define IDS_SH_APP_DESC             2501
